<?php
/*
 *  $Id: all.inc 4113 2002-11-06 04:17:06Z sizzlingmercury $
 *  $Author: sizzlingmercury $
 *  $Date: 2002-11-06 05:17:06 +0100 (mié 06 de nov de 2002) $
 *
 *  all.inc
 *  This file would basically just be to include the core libs
 *  Should make disgning a controller a little easier
 */
      // include all needed function libs
      // The directory structure is not important for this example
      // I would suggest sq_ to avoid possible
      // name conflicts with other scripts
      // new libs are added here so they are available to the entire
      // core without any other file changes
 
 include("sq.inc");
 include("example.inc");
?>